db:
  mongo:
    host: localhost
    port: 27017
    dbName: null
  mysql:
    host: localhost
    user: root
    password: admin
    database: target
    connectionLimit: 10
server:
  host: localhost
  port: 3000
accessControl:
  - http://localhost:8080